/*
 * Copyright 2021-2023 Amazon.com, Inc. or its affiliates. All rights reserved.
 *
 * AMAZON PROPRIETARY/CONFIDENTIAL
 *
 * You may not use this file except in compliance with the terms and
 * conditions set forth in the accompanying LICENSE.txt file.
 *
 * THESE MATERIALS ARE PROVIDED ON AN "AS IS" BASIS. AMAZON SPECIFICALLY
 * DISCLAIMS, WITH RESPECT TO THESE MATERIALS, ALL WARRANTIES, EXPRESS,
 * IMPLIED, OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
 */

#include <ti_drivers_config.h>

#ifndef SIDEWALK_TI_CC13X2_PAL_CRYPTO_CONFIG_H
#define SIDEWALK_TI_CC13X2_PAL_CRYPTO_CONFIG_H

#define CONFIG_CC13X2_PAL_CRYPTO_TRNG_INSTANCE_ID       CONFIG_TRNG_1
#define CONFIG_CC13X2_PAL_CRYPTO_SHA2_INSTANCE_ID       CONFIG_SHA2_0
#define CONFIG_CC13X2_PAL_CRYPTO_AESCMAC_INSTANCE_ID    CONFIG_AESCMAC_0
#define CONFIG_CC13X2_PAL_CRYPTO_AESCTR_INSTANCE_ID     CONFIG_AESCTR_0
#define CONFIG_CC13X2_PAL_CRYPTO_AESGCM_INSTANCE_ID     CONFIG_AESGCM_0
#define CONFIG_CC13X2_PAL_CRYPTO_EDDSA_INSTANCE_ID      CONFIG_EDDSA_0
#define CONFIG_CC13X2_PAL_CRYPTO_ECDSA_INSTANCE_ID      CONFIG_ECDSA_0
#define CONFIG_CC13X2_PAL_CRYPTO_ECDH_INSTANCE_ID       CONFIG_ECDH_1

#endif //SIDEWALK_TI_CC13X2_PAL_CRYPTO_CONFIG_H
