/*
 * Copyright (c) 2021, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

/*
 * This is a copy of a file generated by the secure image build process. It must
 * be manually updated when modifying secure partitions in order to correctly
 * build the non-secure drivers libraries.
 */

#ifndef __PSA_FRAMEWORK_FEATURE_H__
#define __PSA_FRAMEWORK_FEATURE_H__

#define PSA_FRAMEWORK_ISOLATION_LEVEL  1
#define PSA_FRAMEWORK_HAS_MM_IOVEC 0

#endif /* __PSA_FRAMEWORK_FEATURE_H__ */
