#
# GENERATED FILE - DO NOT EDIT!
# This file is generated by ti_export_package, and manual edits will be
# lost after the next call to clean
#


####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was ConfigDrivers.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

find_package("DriversUtils" REQUIRED)
find_package("TrustZone" REQUIRED)
find_package("ThirdPartyEccLib" REQUIRED)
find_package("TiUtils" REQUIRED)
find_package("TiUtilsJson" REQUIRED)
find_package("DriverlibCC13X1CC26X1" REQUIRED)
find_package("Tirtos7Generic" REQUIRED)
find_package("DriverlibCC13X1CC26X1" REQUIRED)
find_package("Tirtos7Generic" REQUIRED)
find_package("DriverlibCC13X2CC26X2" REQUIRED)
find_package("Tirtos7Generic" REQUIRED)
find_package("DriverlibCC13X2CC26X2" REQUIRED)
find_package("Tirtos7Generic" REQUIRED)
find_package("DriverlibCC13X2X7CC26X2X7" REQUIRED)
find_package("Tirtos7Generic" REQUIRED)
find_package("DriverlibCC13X2X7CC26X2X7" REQUIRED)
find_package("Tirtos7Generic" REQUIRED)
find_package("DriverlibCC13X4CC26X3CC26X4" REQUIRED)
find_package("Tirtos7Generic" REQUIRED)
find_package("DriverlibCC13X4CC26X3CC26X4" REQUIRED)
find_package("Tirtos7Generic" REQUIRED)

include("${CMAKE_CURRENT_LIST_DIR}/DriversM4Targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/DriversM4FTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/DriversM33FTargets.cmake")

check_required_components(Drivers)
