#-------------------------------------------------------------------------------
# Copyright (c) 2019-2020 Texas Instruments Incorporated
#
# SPDX-License-Identifier: BSD-3-Clause
#
#-------------------------------------------------------------------------------

# Add back when the Power driver is merged in tidrivers
list(APPEND ALL_SRC_C_S "${SOURCE_REPO}/ti/drivers/power/PowerCC26X2_helpers.c")
list(APPEND ALL_SRC_C_S "${SOURCE_REPO}/ti/drivers/power/PowerCC26X2_calibrateRCOSC_helpers.c")
