/*
 * Copyright (c) 2022-2023, Texas Instruments Incorporated
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is a trimmed-down and modified version of the flash_layout.h
 * generated by the secure image build process. It contains only the defines
 * needed to build the TF-M Internal Trusted Storage (ITS) component, needed for
 * key storage. It has been modified to place the ITS area at the end of flash
 * and remove the PS and NV counter areas. This file is only used for
 * tfm_disabled builds.
 */

#ifndef __FLASH_LAYOUT_H__
#define __FLASH_LAYOUT_H__

#define FLASH0_BASE_S        (0x0)
#define FLASH0_SIZE          (0x100000) /* 1 MB */
#define FLASH0_SECTOR_SIZE   (0x800)    /* 2 KB */
#define FLASH0_PAGE_SIZE     (0x800)    /* 2 KB */
#define FLASH0_PROGRAM_UNIT  (1)        /* Minimum write size */

/* Sector size of the flash hardware */
#define FLASH_AREA_IMAGE_SECTOR_SIZE FLASH0_SECTOR_SIZE
#define FLASH_TOTAL_SIZE             FLASH0_SIZE

/* Internal Trusted Storage (ITS) Service definitions */
#define FLASH_ITS_AREA_OFFSET (FLASH_TOTAL_SIZE - FLASH_ITS_AREA_SIZE)
#define FLASH_ITS_AREA_SIZE   (0x4800) /* 18 KB */

/*
 * Internal Trusted Storage (ITS) Service definitions
 * Note: Further documentation of these definitions can be found in the
 * TF-M ITS Integration Guide.
 */

#define TFM_HAL_ITS_FLASH_DRIVER Driver_FLASH0

#define TFM_HAL_ITS_FLASH_AREA_ADDR    FLASH_ITS_AREA_OFFSET
/* Dedicated flash area for ITS */
#define TFM_HAL_ITS_FLASH_AREA_SIZE    FLASH_ITS_AREA_SIZE
#define TFM_HAL_ITS_SECTOR_SIZE        FLASH_AREA_IMAGE_SECTOR_SIZE
/* Number of ITS_SECTOR_SIZE per block */
#define TFM_HAL_ITS_SECTORS_PER_BLOCK  (1)
/* Specifies the smallest flash programmable unit in bytes */
#define TFM_HAL_ITS_PROGRAM_UNIT FLASH0_PROGRAM_UNIT

#endif /* __FLASH_LAYOUT_H__ */
