/*
 * Copyright (c) 2019-2022, Arm Limited. All rights reserved.
 * Copyright (c) 2021, Cypress Semiconductor Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

 /*
 * This is a copy of a file generated by the secure image build process. It must
 * be manually updated when modifying secure partitions in order to correctly
 * build the non-secure drivers libraries.
 */

#ifndef __PSA_MANIFEST_PID_H__
#define __PSA_MANIFEST_PID_H__

#ifdef __cplusplus
extern "C" {
#endif

#define INTERNAL_STORAGE_SP                                            (300)
#define CRYPTO_SP                                                      (301)

#define TFM_MAX_USER_PARTITIONS                                        (2)

#ifdef __cplusplus
}
#endif

#endif /* __PSA_MANIFEST_PID_H__ */
