/*
 * Copyright (c) 2019-2022, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

/*
 * This is a copy of a file generated by the secure image build process. It must
 * be manually updated when modifying secure partitions in order to correctly
 * build the non-secure drivers libraries.
 */

#ifndef __PSA_MANIFEST_SID_H__
#define __PSA_MANIFEST_SID_H__

#ifdef __cplusplus
extern "C" {
#endif

/******** INTERNAL_STORAGE_SP ********/
#define TI_FLASH_SERVICE_SID                                       (0xAE000070U)
#define TI_FLASH_SERVICE_VERSION                                   (1U)

/******** CRYPTO_SP ********/
#define TI_CRYPTO_SERVICE_SID                                      (0xAE000080U)
#define TI_CRYPTO_SERVICE_VERSION                                  (1U)
#define TFM_ITS_SET_SID                                            (0x00000070U)
#define TFM_ITS_SET_VERSION                                        (1U)
#define TFM_ITS_GET_SID                                            (0x00000071U)
#define TFM_ITS_GET_VERSION                                        (1U)
#define TFM_ITS_GET_INFO_SID                                       (0x00000072U)
#define TFM_ITS_GET_INFO_VERSION                                   (1U)
#define TFM_ITS_REMOVE_SID                                         (0x00000073U)
#define TFM_ITS_REMOVE_VERSION                                     (1U)

#ifdef __cplusplus
}
#endif

#endif /* __PSA_MANIFEST_SID_H__ */
